# Generated by Django 5.1.2 on 2024-11-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='movie_title',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
