# Generated by Django 5.1.2 on 2024-12-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_tickets_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tickets_booked',
        ),
        migrations.AddField(
            model_name='booking',
            name='tickets_booked',
            field=models.ManyToManyField(blank=True, null=True, to='bookings.ticket'),
        ),
    ]
