# Generated by Django 5.1.2 on 2024-11-24 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_seat_remove_ticket_booking_and_more'),
        ('movies', '0003_remove_seat_audit_seat_screening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.screening'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='screening',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='movies.screening'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='movies.seat'),
        ),
    ]
