# Generated by Django 5.1.2 on 2024-11-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_screening_alter_ticket_screening_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_cost',
        ),
    ]
