# Generated by Django 5.1.2 on 2024-11-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='booking',
            name='tickets',
            field=models.ManyToManyField(related_name='bookings', to='bookings.ticket'),
        ),
    ]
