# Generated by Django 5.1.2 on 2024-11-29 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_booking_total_cost_alter_booking_tickets'),
        ('movies', '0011_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='movies.screening'),
        ),
    ]
