# Generated by Django 5.1.2 on 2024-12-06 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('genre', models.TextField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='No description yet.')),
                ('duration', models.DurationField()),
                ('target_audience', models.IntegerField(choices=[(0, '0+'), (12, '12+'), (16, '16+'), (18, '18+')], default=0)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies_images/')),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
                ('date', models.DateField()),
                ('available_seats', models.PositiveIntegerField()),
                ('cinema_hall', models.CharField(max_length=255)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='movies.movie')),
            ],
            options={
                'db_table': 'Screenings',
            },
        ),
    ]
