# Generated by Django 5.1.2 on 2024-11-05 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_cinema', models.CharField(max_length=20)),
                ('total_auditoriums', models.IntegerField()),
            ],
            options={
                'db_table': 'Cinemas',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('genre', models.TextField(default='', max_length=30)),
                ('description', models.TextField(blank=True, default='No description yet.')),
                ('duration', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('target_audience', models.CharField(default='0+', max_length=3)),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_name', models.TextField(max_length=30)),
                ('total_seats', models.PositiveIntegerField(default=0)),
                ('cinema', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='auditoriums', to='movies.cinema')),
            ],
            options={
                'db_table': 'Auditoriums',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='')),
                ('last_name', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
                ('date', models.DateField(default='')),
                ('seats_remaining', models.IntegerField(default=0)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='movies.audit')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='movies.movie')),
            ],
            options={
                'db_table': 'Screenings',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('number', models.CharField(default=0, max_length=2)),
                ('is_taken', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.audit')),
            ],
            options={
                'db_table': 'Seats',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('card_number', models.CharField(default=0, max_length=20)),
                ('name_on_card', models.CharField(default='', max_length=20)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.customer')),
                ('screening', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.screening')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.seat')),
            ],
            options={
                'db_table': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.booking')),
            ],
            options={
                'db_table': 'Tickets',
            },
        ),
    ]
