# Generated by Django 5.1.2 on 2024-11-12 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_cinema', models.CharField(max_length=20)),
                ('total_auditoriums', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'Cinemas',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('genre', models.TextField(default='', max_length=30)),
                ('description', models.TextField(blank=True, default='No description yet.')),
                ('duration', models.PositiveIntegerField(default=0)),
                ('target_audience', models.IntegerField(choices=[(0, '0+'), (12, '12+'), (16, '16+'), (18, '18+')], default=0)),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.PositiveIntegerField(default=1)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoriums', to='movies.cinema')),
            ],
            options={
                'db_table': 'Auditoriums',
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
                ('date', models.DateField()),
                ('seats_remaining', models.PositiveIntegerField()),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='movies.audit')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='movies.movie')),
            ],
            options={
                'db_table': 'Screenings',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('number', models.CharField(max_length=2)),
                ('is_taken', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.audit')),
            ],
            options={
                'db_table': 'Seats',
            },
        ),
    ]
