# Generated by Django 5.1.2 on 2024-11-24 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='audit',
        ),
        migrations.AddField(
            model_name='seat',
            name='screening',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.screening'),
        ),
    ]
