# Generated by Django 5.1.2 on 2024-11-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_seat_audit_seat_screening'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='adress',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
