# Generated by Django 5.1.2 on 2024-11-26 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='screening',
        ),
        migrations.AddField(
            model_name='seat',
            name='auditorium',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.audit'),
        ),
    ]
